# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='\u30e6\u30fc\u30b6ID')),
                ('adminFlag', models.BooleanField(default=False, verbose_name='\u7ba1\u7406\u8005\u30d5\u30e9\u30b0')),
                ('LoginTimes', models.BigIntegerField()),
                ('recent_login_date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '\u30e6\u30fc\u30b6',
                'verbose_name_plural': '\u30e6\u30fc\u30b6',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=30)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('Question', models.CharField(max_length=200)),
                ('AnswerNo', models.BigIntegerField()),
                ('Answer', models.CharField(max_length=200)),
                ('Withdrawal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.CharField(max_length=100)),
                ('Answer', models.CharField(max_length=200)),
                ('URL', models.URLField(max_length=300)),
                ('NextAnswerNo', models.BigIntegerField()),
                ('Question', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=30, unique=True, verbose_name='\u30e6\u30fc\u30b6ID')),
            ],
        ),
    ]
