# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='Question',
            field=models.CharField(max_length=200),
        ),
    ]
