# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180904_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.CharField(blank=True, max_length=10)),
                ('Q2', models.CharField(blank=True, max_length=10)),
                ('Q3', models.CharField(blank=True, max_length=10)),
                ('Q4', models.CharField(blank=True, max_length=10)),
                ('Q5', models.CharField(blank=True, max_length=10)),
                ('A1', models.CharField(blank=True, max_length=10)),
                ('A2', models.CharField(blank=True, max_length=10)),
                ('A3', models.CharField(blank=True, max_length=10)),
                ('A4', models.CharField(blank=True, max_length=10)),
                ('A5', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Memo',
        ),
        migrations.AddField(
            model_name='qa',
            name='NextQA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.NextQA'),
            preserve_default=False,
        ),
    ]
