# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20180907_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='IdPerUser',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
