# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20180907_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u30e6\u30fc\u30b6\u540d\u79f0'),
        ),
    ]
