# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20180910_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='LoginTimes',
        ),
    ]
