# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_authuser_logintimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='userKey',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
