# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_qa_userkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='IdPerUser',
            field=models.IntegerField(),
        ),
    ]
