# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20180920_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
