# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20190115_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='is_public',
            field=models.TextField(choices=[('0', 'テスト'), ('1', '公開')], default='0', max_length=1),
        ),
    ]
