# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_auto_20190116_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa',
            name='is_public',
        ),
    ]
