# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_auto_20190116_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='qa',
            name='status',
        ),
    ]
