# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0035_auto_20190116_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='is_public',
            field=models.BooleanField(choices=[(False, 'テスト'), (True, '公開')], default=False),
        ),
    ]
