# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0036_auto_20190116_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
