# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0037_auto_20190116_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='is_public',
            field=models.BooleanField(choices=[(True, '公開'), (False, 'テスト')], default=False),
        ),
    ]
