# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-20 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_auto_20190120_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=30)),
                ('userKey', models.CharField(max_length=100)),
                ('adminFlag', models.BooleanField(default=False)),
            ],
        ),
    ]
