# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-20 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0041_adminflag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminFlag',
        ),
    ]
