# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0043_adminflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='log',
            name='ScreenId',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='qa',
            name='Answer',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='qa',
            name='Keyword',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='qa',
            name='URL',
            field=models.URLField(default=' ', max_length=300),
        ),
    ]
