# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0044_auto_20190209_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='is_staff',
        ),
    ]
