# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0045_remove_authuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
